# name: Deplyment Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/ckeckout@v3
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v3
  